#!/bin/bash
set -e

AFTER="2024-06"

# Convert PDF files to markdown.
src/process docs/FORPD $AFTER
src/process docs/SMUD $AFTER
src/process docs/SJUSD $AFTER
src/process docs/SMFD $AFTER
src/process docs/FOWD $AFTER
src/process docs/LRCCD $AFTER
src/process docs/SJWD $AFTER
src/process docs/SCOE $AFTER
