#!/bin/bash
set -e


src/gather docs/SMUD 2024-08 > "SMUD since August 2024.md"
src/gather docs/SMFD 2024-08 > "SMFD since August 2024.md"
src/gather docs/SJWD 2024-10 > "SJWD since October 2024.md"
src/gather docs/FOWD 2024-09 > "FOWD since September 2024.md"
src/gather docs/FORPD 2024-10 > "FORPD since October 2024.md"
src/gather docs/SJUSD 2024-10 > "SJUSD since October 2024.md"

# src/gather docs/LRCCD 2024-09
# src/gather docs/SCOE 2024-09


