#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <directory> <after_date>"
    exit 1
fi

DIR="$1"
AFTER="$2"

ALL_FILES=$(find "$DIR" -mindepth 2 -maxdepth 2 -type f -name "summary.md")
PROCESS_FILES=$(echo "$ALL_FILES" | awk -v after="$DIR/$AFTER" '$0 >= after')

# Find all summary.md files in date subdirectories
echo "$PROCESS_FILES" | while read summary_file; do
    # Output contents of summary file
    cat "$summary_file"
    echo
    echo
done
